### ISSUE TITLE
xdebug.mode changes for v3.0.0

### ISSUE THREAD

**Issue by peterwilsoncc** [Chassis/Xdebug#66]
In Version 3.0.0 xdebug.mode changed to enable/disable items differently.

The `var_dump()` override is no longer enabled in `debug` mode, the mode needs to be set to `debug,develop`.

References:
* https://xdebug.org/updates#x_3_0_0
* https://xdebug.org/docs/all_settings#mode

No PR, I am afraid, as I am unsure if other modes need to be enabled for backward compatibility.

**System**
OS: macOS Big Dur (11.1)
Vagrant: 2.2.10
VM type: VirtualBox 6.1.16 r140961
Config: [config.local.yaml.zip](https://github.com/Chassis/Xdebug/files/5799105/config.local.yaml.zip)
No global extensions

**Comment by BronsonQuick** [comment]
Sorry for the epic delay on this Sir. I've tested your change on 5.6 -> 8.0 and I can confirm that it's working and backwards compatible. Thanks for hunting down the cause of this.

**Comment by BronsonQuick** [comment]
@peterwilsoncc Also, you could trim your `config.local.yaml` down to this:
```
# Chassis Configuration

# Domain names to use for Vagrant
#
# The first name will be used as the machine's name, subsequent names will be
# aliased in your hosts file and in nginx
#
# (When overriding, include vagrant.local if you need it)
hosts:
    - am-plugins.local

# Site Configuration
# (When overriding, include all values)
site:
    name: Awesome Motive Plugin Dev

# Admin configuration
# (When overriding, include all values)
admin:
    user: admin
    email: wilson@peterwilson.cc
    password: password

# Install a list of extensions automatically
extensions:
  - mailhog
  - xdebug
  - phpunit

# PHP version
# Values: 5.6, 7.0, 7.1, 7.2, 7.3, 7.4, 8.0 (or 5.6.30)
php: 7.2
```

You only need to specify overrides the defaults will be merged in 😁
